[tool.poetry]
name = "vacany-hh"
version = "0.1.0"
description = ""
authors = ["ro_k_ <ro_k_sana@mail.ru>"]
readme = "README.md"
packages = [{include = "vacany_hh"}]

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
